[package]
name = "tcc"
version = "0.1.0"
authors = ["Daniel Kolsoi <thadan64@gmail.com>"]
edition = "2018"

[dependencies]
c2rust-bitfields = { path = "../../../../c2rust-bitfields" }
num-traits = "0.2.6"
f128 = "0.2.2"

[build-dependencies]
cc = "1.0"
